apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::084446270647:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::084446270647:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KK354O3ELCAL
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::084446270647:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n  groups:\n    - system:masters\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-02-15T17:33:46Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:mapRoles":{},"f:mapUsers":{}}},"manager":"eksctl.exe","operation":"Update","time":"2021-02-15T17:33:46Z"}],"name":"aws-auth","namespace":"kube-system","resourceVersion":"1317","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"9b87a6ba-21ef-4e93-a6ab-193bbe02de35"}}
  creationTimestamp: "2021-02-15T17:33:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-15T17:33:46Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-15T18:30:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10860"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9b87a6ba-21ef-4e93-a6ab-193bbe02de35
